sudo: required

language: python

python:
  - "3.6"

branches:
  - master
  - development
  - /.*release.*/

services:
  - docker

before_script:
  - docker build -t pdf2front .

script:
  - docker run pdf2front npm run build

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: development
  - provider: script
    script: bash scripts/sendZip.sh
    on:
      branch: master

addons:
  apt:
    packages:
      - docker-ce
