version: '3'
services:
  front:
    build: .
    command: npm run dev
    volumes:
        - ./pdf2cash_front:/app
        - /app/node_modules
    ports:
     - "3000:3000"
    environment:
    - INVOICE_DOMAIN=http://localhost:8000
    - WORKER_DOMAIN=http://localhost:8075
